use warp::Filter;

#[tokio::main]
async fn main() {
    // GET /hello/warp => 200 OK with body "Hello, warp!"
    let hello = warp::path!("hello" / String / usize / String / usize)
        .map(|a, b, c, d| format!("Hello, {} {} {} {}!", a, b, c, d));

    let routes = warp::path("api")
        .and(
            hello
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello)
                .or(hello),
        );

    warp::serve(routes)
        .run(([127, 0, 0, 1], 3030))
        .await;
}